version: "3"
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  server:
    build:
      context: "src"
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /root/.npm/_logs
      - /app/node_modules
      - ./src:/app
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - SECRET=aLb8SrGRrBrbDRfqQczF
